
// result :  ["back","cardio","chest","lower arms","lower legs","neck","shoulders","upper arms","upper legs","waist"]

const back = [
  { label: 'Alternate Lateral Pulldown' },
    { label: 'Archer Pull Up' },
    { label: 'Assisted Parallel Close Grip Pull-up' },
    { label: 'Assisted Pull-up' },
    { label: 'Assisted Standing Chin-up' },
    { label: 'Assisted Standing Pull-up' },
    { label: 'Back Extension On Exercise Ball' },
    { label: 'Back Lever' },
    { label: 'Back Pec Stretch' },
    { label: 'Band Assisted Pull-up' },
    { label: 'Astride Jumps (Male)' },
    { label: 'Back And Forth Step' },
    { label: 'Bear Crawl' },
    { label: 'Burpee' },
    { label: 'Cycle Cross Trainer' },
    { label: 'Dumbbell Burpee' },
    { label: 'Half Knee Bends (Male)' },
    { label: 'High Knee Against Wall' },
    { label: 'Jack Burpee' },
    { label: 'Jack Jump (Male)' },
    {label: 'Barbell Deadlift'},
  {label: 'Barbell Sumo Deadlift'},
]

const chest = [
  { label: 'Archer Push Up' },
    { label: 'Assisted Chest Dip (Kneeling)' },
    { label: 'Assisted Seated Pectoralis Major Stretch With Stability Ball'},
    { label: 'Assisted Wide-grip Chest Dip (Kneeling)' },
    { label: 'Band One Arm Twisting Chest Press' },
    { label: 'Band Bench Press' },
    { label: 'Barbell Bench Press' },
    { label: 'Barbell Decline Bench Press' },
    { label: 'Barbell Decline Wide-grip Press' },
    { label: 'Barbell Decline Pullover' },
    { label: 'Barbell Close-grip Bench Press' },
    { label: 'Band Close-grip Push-up' },
    { label: 'Barbell Incline Bench Press' },
  { label: 'Barbell Incline Close Grip Bench Press' },
  { label: 'Barbell Incline Reverse-grip Press' },
  { label: 'Barbell Reverse Grip Incline Bench Press' },
  { label: 'Cable Incline Bench Press' },
]

const bicepsandForearm =  [
  { label: 'Band Reverse Wrist Curl' },
    { label: 'Band Wrist Curl' },
    { label: 'Barbell Palms Down Wrist Curl Over A Bench' },
    { label: 'Barbell Palms Up Wrist Curl Over A Bench' },
    { label: 'Barbell Revers Wrist Curl V. 2' },
    { label: 'Barbell Reverse Wrist Curl' },
    { label: 'Barbell Standing Back Wrist Curl' },
    { label: 'Barbell Wrist Curl' },
    { label: 'Barbell Wrist Curl V. 2' },
    { label: 'Cable Reverse Wrist Curl' },
    { label: 'Band Alternating Biceps Curl' },
    { label: 'Band Concentration Curl' },
    { label: 'Band One Arm Overhead Biceps Curl' },
    { label: 'Barbell Alternate Biceps Curl' },
    { label: 'Barbell Biceps Curl (With Arm Blaster)' },
    { label: 'Dumbbell Alternate Biceps Curl' },
  { label: 'Dumbbell Alternate Biceps Curl (With Arm Blaster)' },
  { label: 'Dumbbell Alternate Hammer Preacher Curl' },
  { label: 'Dumbbell Alternate Preacher Curl' },
  { label: 'Dumbbell Alternate Seated Hammer Curl' },
  { label: 'Dumbbell Alternate Side Press' },
  {
    label: 'Dumbbell Alternating Bicep Curl With Leg Raised On Exercise Ball'
  },
  { label: 'Dumbbell Alternating Seated Bicep Curl On Exercise Ball' },
]

const triceps = [
  { label: 'Assisted Standing Triceps Extension (With Towel)' },
    { label: 'Assisted Triceps Dip (Kneeling)' },
    { label: 'Band Side Triceps Extension' },
    { label: 'Barbell Close-grip Bench Press' },
    { label: 'Band Close-grip Push-up' },
    { label: 'Band Bench Press' },
    { label: 'Barbell Bench Press' },
    { label: 'Barbell Decline Bench Press' },
    { label: 'Barbell Decline Wide-grip Press' },
    { label: 'Barbell Incline Bench Press' },
  { label: 'Barbell Incline Close Grip Bench Press' },
  { label: 'Barbell Incline Reverse-grip Press' },
  { label: 'Barbell Reverse Grip Incline Bench Press' },
  { label: 'Cable Incline Bench Press' },
]

const shoulders = [
  { label: 'Neck Side Stretch' },
    { label: 'Side Push Neck Stretch' },
    { label: 'Band Front Lateral Raise' },
    { label: 'Band Front Raise' },
    { label: 'Band Reverse Fly' },
    { label: 'Band Shoulder Press' },
    { label: 'Band Standing Rear Delt Row' },
    { label: 'Band Twisting Overhead Press' },
    { label: 'Band Y-raise' },
    { label: 'Barbell Front Raise' },
    { label: 'Barbell One Arm Snatch' },
    { label: 'Barbell Rear Delt Raise' },
    { label: 'Dumbbell Arnold Press' },
  { label: 'Dumbbell Arnold Press V. 2' },
  {label : 'Dumbbell Incline Shoulder Raise'},
  {label : 'Barbell Incline Shoulder Raise'},
]
const legs = [
  { label: 'Ankle Circles' },
    { label: 'Assisted Lying Calves Stretch' },
    { label: 'Band Single Leg Calf Raise' },
    { label: 'Band Single Leg Reverse Calf Raise' },
    { label: 'Band Two Legs Calf Raise - (Band Under Both Legs) V. 2' },
    { label: 'Barbell Floor Calf Raise' },
    { label: 'Barbell Seated Calf Raise' },
    { label: 'Barbell Standing Calf Raise' },
    { label: 'Barbell Standing Leg Calf Raise' },
    { label: 'All Fours Squad Stretch' },
    { label: 'Arms Apart Circular Toe Touch (Male)' },
    { label: 'Assisted Lying Glutes Stretch' },
    { label: 'Assisted Lying Gluteus And Piriformis Stretch' },
    { label: 'Assisted Prone Hamstring' },
    { label: 'Assisted Prone Lying Quads Stretch' },
    { label: 'Assisted Side Lying Adductor Stretch' },
    { label: 'Backward Jump' },
    { label: 'Balance Board' },
    { label: 'Band Bent-over Hip Extension' },
    { label: '3/4 Sit-up' },
    { label: '45° Side Bend' },
  { label: 'Air Bike' },
  { label: 'Alternate Heel Touchers' },
  { label: 'Arm Slingers Hanging Bent Knee Legs' },
  { label: 'Arm Slingers Hanging Straight Legs' },
  { label: 'Arms Overhead Full Sit-up (Male)' },
  { label: 'Assisted Hanging Knee Raise' },
  { label: 'Assisted Hanging Knee Raise With Throw Down' },
  { label: 'Assisted Lying Leg Raise With Lateral Throw Down' },
  {label: 'Barbell Full Squat'},
  {label: 'Barbell Front Squat'},
  {label: 'Barbell Front Chest Squat'},
  {label: 'Barbell Romanian Deadlift'},
  {label: 'Barbell Single Leg Deadlift'},
]

const exercises = [
    { label: 'Alternate Lateral Pulldown' },
    { label: 'Archer Pull Up' },
    { label: 'Assisted Parallel Close Grip Pull-up' },
    { label: 'Assisted Pull-up' },
    { label: 'Assisted Standing Chin-up' },
    { label: 'Assisted Standing Pull-up' },
    { label: 'Back Extension On Exercise Ball' },
    { label: 'Back Lever' },
    { label: 'Back Pec Stretch' },
    { label: 'Band Assisted Pull-up' },
    { label: 'Astride Jumps (Male)' },
    { label: 'Back And Forth Step' },
    { label: 'Bear Crawl' },
    { label: 'Burpee' },
    { label: 'Cycle Cross Trainer' },
    { label: 'Dumbbell Burpee' },
    { label: 'Half Knee Bends (Male)' },
    { label: 'High Knee Against Wall' },
    { label: 'Jack Burpee' },
    { label: 'Jack Jump (Male)' },
    { label: 'Archer Push Up' },
    { label: 'Assisted Chest Dip (Kneeling)' },
    { label: 'Assisted Seated Pectoralis Major Stretch With Stability Ball'},
    { label: 'Assisted Wide-grip Chest Dip (Kneeling)' },
    { label: 'Band Bench Press' },
    { label: 'Band One Arm Twisting Chest Press' },
    { label: 'Barbell Bench Press' },
    { label: 'Barbell Decline Bench Press' },
    { label: 'Barbell Decline Pullover' },
    { label: 'Barbell Decline Wide-grip Press' },
    { label: 'Band Reverse Wrist Curl' },
    { label: 'Band Wrist Curl' },
    { label: 'Barbell Palms Down Wrist Curl Over A Bench' },
    { label: 'Barbell Palms Up Wrist Curl Over A Bench' },
    { label: 'Barbell Revers Wrist Curl V. 2' },
    { label: 'Barbell Reverse Wrist Curl' },
    { label: 'Barbell Standing Back Wrist Curl' },
    { label: 'Barbell Wrist Curl' },
    { label: 'Barbell Wrist Curl V. 2' },
    { label: 'Cable Reverse Wrist Curl' },
    { label: 'Ankle Circles' },
    { label: 'Assisted Lying Calves Stretch' },
    { label: 'Band Single Leg Calf Raise' },
    { label: 'Band Single Leg Reverse Calf Raise' },
    { label: 'Band Two Legs Calf Raise - (Band Under Both Legs) V. 2' },
    { label: 'Barbell Floor Calf Raise' },
    { label: 'Barbell Seated Calf Raise' },
    { label: 'Barbell Standing Calf Raise' },
    { label: 'Barbell Standing Leg Calf Raise' },

    { label: 'Neck Side Stretch' },
    { label: 'Side Push Neck Stretch' },
    { label: 'Band Front Lateral Raise' },
    { label: 'Band Front Raise' },
    { label: 'Band Reverse Fly' },
    { label: 'Band Shoulder Press' },
    { label: 'Band Standing Rear Delt Row' },
    { label: 'Band Twisting Overhead Press' },
    { label: 'Band Y-raise' },
    { label: 'Barbell Front Raise' },
    { label: 'Barbell One Arm Snatch' },
    { label: 'Barbell Rear Delt Raise' },


    { label: 'Assisted Standing Triceps Extension (With Towel)' },
    { label: 'Assisted Triceps Dip (Kneeling)' },
    { label: 'Band Close-grip Push-up' },
    { label: 'Band Side Triceps Extension' },
    { label: 'Barbell Close-grip Bench Press' },

    { label: 'Band Alternating Biceps Curl' },
    { label: 'Band Concentration Curl' },
    { label: 'Band One Arm Overhead Biceps Curl' },
    { label: 'Barbell Alternate Biceps Curl' },
    { label: 'Barbell Biceps Curl (With Arm Blaster)' },

    { label: 'All Fours Squad Stretch' },
    { label: 'Arms Apart Circular Toe Touch (Male)' },
    { label: 'Assisted Lying Glutes Stretch' },
    { label: 'Assisted Lying Gluteus And Piriformis Stretch' },
    { label: 'Assisted Prone Hamstring' },
    { label: 'Assisted Prone Lying Quads Stretch' },
    { label: 'Assisted Side Lying Adductor Stretch' },
    { label: 'Backward Jump' },
    { label: 'Balance Board' },
    { label: 'Band Bent-over Hip Extension' },
    { label: '3/4 Sit-up' },
  { label: '45° Side Bend' },
  { label: 'Air Bike' },
  { label: 'Alternate Heel Touchers' },
  { label: 'Arm Slingers Hanging Bent Knee Legs' },
  { label: 'Arm Slingers Hanging Straight Legs' },
  { label: 'Arms Overhead Full Sit-up (Male)' },
  { label: 'Assisted Hanging Knee Raise' },
  { label: 'Assisted Hanging Knee Raise With Throw Down' },
  { label: 'Assisted Lying Leg Raise With Lateral Throw Down' },

  { label: 'Barbell Incline Bench Press' },
  { label: 'Barbell Incline Close Grip Bench Press' },
  { label: 'Barbell Incline Reverse-grip Press' },
  { label: 'Barbell Reverse Grip Incline Bench Press' },
  { label: 'Cable Incline Bench Press' },
  { label: 'Barbell Incline Row' },
  { label: 'Barbell Incline Shoulder Raise' },
  { label: 'Barbell Prone Incline Curl' },
  { label: 'Barbell Reverse Grip Incline Bench Row' },
  { label: 'Bodyweight Incline Side Plank' },


  { label: 'Barbell Decline Bent Arm Pullover' },
  { label: 'Barbell Decline Close Grip To Skull Press' },
  { label: 'Barbell Decline Wide-grip Pullover' },
  { label: 'Barbell Reverse Grip Decline Bench Press' },
  { label: 'Cable Decline Fly' },
  { label: 'Cable Decline One Arm Press' },
  { label: 'Cable Decline Press' },

  { label: 'Dumbbell Alternate Biceps Curl' },
  { label: 'Dumbbell Alternate Biceps Curl (With Arm Blaster)' },
  { label: 'Dumbbell Alternate Hammer Preacher Curl' },
  { label: 'Dumbbell Alternate Preacher Curl' },
  { label: 'Dumbbell Alternate Seated Hammer Curl' },
  { label: 'Dumbbell Alternate Side Press' },
  {
    label: 'Dumbbell Alternating Bicep Curl With Leg Raised On Exercise Ball'
  },
  { label: 'Dumbbell Alternating Seated Bicep Curl On Exercise Ball' },
  { label: 'Dumbbell Arnold Press' },
  { label: 'Dumbbell Arnold Press V. 2' },



  {label: 'Barbell Full Squat'},
  {label: 'Barbell Front Squat'},
  {label: 'Barbell Front Chest Squat'},
  {label: 'Barbell Deadlift'},
  {label: 'Barbell Sumo Deadlift'},
  {label: 'Barbell Romanian Deadlift'},
  {label: 'Barbell Single Leg Deadlift'},

  {label : 'Dumbbell Incline Shoulder Raise'},
  {label : 'Barbell Incline Shoulder Raise'},

  ];


const split = [back,chest,bicepsandForearm,triceps,shoulders,legs];
module.exports = {exercises,split};